#This is the makfile for the dicegame project

compile:
	g++ project-1.cpp -Wall -o p1.exe #This compiles the program and names the run file accordingly

run:
	./p1.exe #Runs the out file

clean:
	rm *.exe #Cleans the directory and gets rid of the .exe file
